package pick.com.app.webservices

class Urls {

    companion object {
        //val BASE_URL = "https://in.endivesoftware.com/sites/pick/api/"
        val BASE_URL = "http://pick.com.sa/api/"
        var REGISTER_URL="user_register"
        var REGISTER_URL_OWNER="owner_register"
        var SEND_OTP_URL="send_otp"
        var SOCIAL_LOGIN_URL="social_login"
        var SET_PASSWORD_URL="set_password"
        var UPDATE_PROFILE_URL="update_profile"
        var VERIFY_OTP_URL= "verify_otp"
        var LOGIN = "user_login"
        var OWNER_LOGIN = "owner_login"
        var LOGOUT = "logout"
        var CHANGE_PASSWORD = "change_password"
        var GET_PROFILE = "get_profile"
        var GET_CountriesCode = "get_countries"
        var ADD_VECHICLE = "add_vehicle"
        var UPDATE_VECHICLE = "update_vehicle "
        var GET_MODELS = "get_models"
        var GET_SEATERS = "get_seaters"
        var GET_FUEL_TYPE= "get_fuel_types"
        var GET_YEARS= "get_years"
        var GET_TRANSMISSION= "get_vehicle_transmissions"
        var GET_VEHICLE_TYPES= "get_vehicle_types"
        var BULK_AVAILABLE_LIST= "bulk_available_list"
        var VEHICLE_LISTING= "vehicle_listing"
        var UPDATE_VEHICLE_AVAILIBITY= "update_vehicle_availabality"
        var SEARCH_VEHICLE= "search_vehicle"
        var GET_VEHICLE_DETAILS= "get_vehicle_details"
        var VEHICLE_BOOKING= "vehicle_booking"
        var DELETE_ACCOUNT= "delete_bank_account"
        var BOOKING_PAYMENT="booking_payment"
        var ADD_ACCOUNT= "add_bank_account"
        var UPDATE_ACCOUNT= "update_bank_account"
        var GET_NEWBOOKING= "getNewBookingList"
        var GET_OngoingBookingsOwner= "OngoingBookingsOwner"
        var GET_PastBookingsOwner= "PastBookingsOwner"
        var GET_OngoingBookingsUser= "OngoingBookingsUser"
        var GET_PastBookingsUser= "PastBookingsUser"
        var CHANGE_BOKING_STATUS= "change_booking_status"
        var CHANGE_BOKING_STATUS_USER= "change_booking_status_user"
        var CANCEL_BOOKING_USER= "cancel_booking_user"
        var SAVE_CHECKUP_BEFORE= "saveCheckupBeforeDetails"
        var SAVE_CHECKUP_AFTER= "saveCheckAfterDetails"
        var IMAGE_UPLOAD= "imageUpload"
        var IMAGE_REMOVE= "remove_image"
        var REMOVEALLIMAGES= "remove_images_for_booking"
        var USER_REPORT= "user_report"
        var GET_CITIES= "get_cities"
        var GET_DROP_CITIES= "get_drop_cities"
        var RATING_USER= "rating_user"
        var EXTEND_BOOKING = "extend_booking"
        var FAVOURITE_VEHICLE = "favourite_vehicle"
        var MY_FAVOURITE_VEHICLE = "my_favourite_vehicles"
        var GET_FILTERS = "get_filters"
        var DELETE_VEHICLE = "delete_vehicle"
        var SAVE_CONTACT_US = "save_contact_us"
        var GET_CONTACT_US = "get_contact_us"
        var GET_USER_AVAILABALITY = "get_user_availabality"
        var OWNER_AVAILABALITY = "owner_availability"
        var SAVE_MANAGE_AVAILABILITY = "save_manage_availability"
        var USER_WALLET = "get_wallet"
        var MAKE_PAYMENT = "make_payment"
        var MAKE_PAYMENT_WALLET = "make_payment_wallet"
        var ADDWALLETAMOUNT="addamount_wallet"
        var SETTLEMENT="settlementRequest"
        var BANK="banks"
        var FINALPAYMENT="finalPayment"
        var REQUEST="request"
        var GETPAYABLE="payable"
        var USERWALLET="user_wallet"
        var Rejectstatus="rejectStatus"
        var CANCELOWNER="cancelOwner"
        var PDF="dfile"
        var GETNOTIFICATION="get_notification_list"

    }


}
